"""add membership uniqueness constraint

Revision ID: 28f1d0585bb2
Revises: 4f2d88ffb070
Create Date: 2026-08-12 15:47:57.997580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f1d0585bb2'
down_revision: Union[str, Sequence[str], None] = '4f2d88ffb070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_membership_user_organization', 'memberships', ['user_id', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_membership_user_organization', 'memberships', type_='unique')
    # ### end Alembic commands ###
